<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-KC124AK" failures="0" tests="5" name="DataDriventesting.DataDrivenTestingMethod" time="0.052" errors="1" timestamp="2025-04-27T12:59:00 IST" skipped="0">
  <testcase classname="DataDriventesting.DataDrivenTestingMethod" name="getTestData" time="0.042"/>
  <system-out/>
  <testcase classname="DataDriventesting.DataDrivenTestingMethod" name="getTestData" time="0.003"/>
  <system-out/>
  <testcase classname="DataDriventesting.DataDrivenTestingMethod" name="getTestData" time="0.002"/>
  <system-out/>
  <testcase classname="DataDriventesting.DataDrivenTestingMethod" name="getTestData" time="0.003"/>
  <system-out/>
  <testcase classname="DataDriventesting.DataDrivenTestingMethod" name="testObjData" time="0.002">
    <error message="
[public void DataDriventesting.DataDrivenTestingMethod.testObjData(java.lang.Object,java.lang.Object,java.lang.Object,java.lang.Object,java.lang.Object)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testObjData([Parameter{index=0, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.Object, declaredAnnotations=[]}])
Arguments: [(java.lang.String) Nihal@gmail.com,(java.lang.String) Nihal@123,(java.lang.String) Logged in sucess]" type="org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void DataDriventesting.DataDrivenTestingMethod.testObjData(java.lang.Object,java.lang.Object,java.lang.Object,java.lang.Object,java.lang.Object)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testObjData([Parameter{index=0, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.Object, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.Object, declaredAnnotations=[]}])
Arguments: [(java.lang.String) Nihal@gmail.com,(java.lang.String) Nihal@123,(java.lang.String) Logged in sucess]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:914)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- testObjData -->
  <system-out/>
</testsuite> <!-- DataDriventesting.DataDrivenTestingMethod -->
